# Site settings
title: IBM Cloud Pak for Data - Workshops
description: >-
  In this workshop, we will walk through creating a machine learning model using IBM Watson Machine Learning and IBM DB2 while utilizing IBM Cloud Pak for Data.
baseurl: "/ibm-cpd-workshop" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tmarkiewicz
github_username:  tmarkiewicz

# Build settings
markdown: kramdown
theme: minima

# Authors
authors:
  - name: Tom Markiewicz
    twitter: tmarkiewicz
    github: tmarkiewicz

exclude: ['_discovery/app/']

collections:
  # object_detection:
  #   output: true
  #   permalink: /object-detection/:path:output_ext
  cpd-wml:
    output: true
    permalink: /cpd-wml/:path:output_ext
  accelerator:
    output: true
    permalink: /accelerator/:path:output_ext
  discovery:
    output: true
    permalink: /discovery/:path:output_ext

defaults:
  - scope:
      path: ""
      type: "discovery"
    values:
      layout: index
  - scope:
      path: ""
      type: "accelerator"
    values:
      layout: index
  - scope:
      path: ""
      type: "cpd-wml"
    values:
      layout: index
